/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { SpendRegistry, SpendRegistryInterface } from "../SpendRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "stepId",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "memo",
        type: "string",
      },
    ],
    name: "SpendLogged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "stepId",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "memo",
        type: "string",
      },
    ],
    name: "logSpend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101f0806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063a9097ee414610030575b600080fd5b61004361003e3660046100de565b610045565b005b336001600160a01b03167f8ab773cdc4a32f91ad9d097e01a66feaba8aeab0256763b33a7eb85e64cb37a98686868686604051610086959493929190610181565b60405180910390a25050505050565b60008083601f8401126100a757600080fd5b50813567ffffffffffffffff8111156100bf57600080fd5b6020830191508360208285010111156100d757600080fd5b9250929050565b6000806000806000606086880312156100f657600080fd5b853567ffffffffffffffff8082111561010e57600080fd5b61011a89838a01610095565b909750955060208801359450604088013591508082111561013a57600080fd5b5061014788828901610095565b969995985093965092949392505050565b81835281816020850137506000828201602090810191909152601f909101601f19169091010190565b606081526000610195606083018789610158565b85602084015282810360408401526101ae818587610158565b9897505050505050505056fea26469706673582212209b31260f623058463029ffb789e0c0de60707cd287ea0ae507d6f2d1d7a32a7d64736f6c63430008180033";

type SpendRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SpendRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SpendRegistry__factory extends ContractFactory {
  constructor(...args: SpendRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SpendRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SpendRegistry__factory {
    return super.connect(runner) as SpendRegistry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SpendRegistryInterface {
    return new Interface(_abi) as SpendRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SpendRegistry {
    return new Contract(address, _abi, runner) as unknown as SpendRegistry;
  }
}
