/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SpendRegistry } from "./SpendRegistry";
export * as factories from "./factories";
export { SpendRegistry__factory } from "./factories/SpendRegistry__factory";
