/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SpendRegistryInterface extends Interface {
  getFunction(nameOrSignature: "logSpend"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SpendLogged"): EventFragment;

  encodeFunctionData(
    functionFragment: "logSpend",
    values: [string, BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "logSpend", data: BytesLike): Result;
}

export namespace SpendLoggedEvent {
  export type InputTuple = [
    payer: AddressLike,
    stepId: string,
    amount: BigNumberish,
    memo: string
  ];
  export type OutputTuple = [
    payer: string,
    stepId: string,
    amount: bigint,
    memo: string
  ];
  export interface OutputObject {
    payer: string;
    stepId: string;
    amount: bigint;
    memo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SpendRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SpendRegistry;
  waitForDeployment(): Promise<this>;

  interface: SpendRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  logSpend: TypedContractMethod<
    [stepId: string, amount: BigNumberish, memo: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "logSpend"
  ): TypedContractMethod<
    [stepId: string, amount: BigNumberish, memo: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "SpendLogged"
  ): TypedContractEvent<
    SpendLoggedEvent.InputTuple,
    SpendLoggedEvent.OutputTuple,
    SpendLoggedEvent.OutputObject
  >;

  filters: {
    "SpendLogged(address,string,uint256,string)": TypedContractEvent<
      SpendLoggedEvent.InputTuple,
      SpendLoggedEvent.OutputTuple,
      SpendLoggedEvent.OutputObject
    >;
    SpendLogged: TypedContractEvent<
      SpendLoggedEvent.InputTuple,
      SpendLoggedEvent.OutputTuple,
      SpendLoggedEvent.OutputObject
    >;
  };
}
